[package]
name = "rdiff"
version = "0.1.0"
authors = ["Shoaib <shoaib.ahmed@slock.it>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adler32 = "1.2.0"
md5 = "0.7.0"
